### ISSUE TITLE
The code showing error during execution

### ISSUE THREAD

**Issue by RiyaSamanta** [groundhogday321/python-radar-charts#1]
ValueError: The number of FixedLocator locations (6), usually from a call to set_ticks, does not match the number of ticklabels (5).

**Comment by groundhogday321** [comment]
If Receiving Error for Matplotlib Radar Chart: ValueError: The number of FixedLocator locations (6), usually from a call to set_ticks, does not match the number of ticklabels (5).
A simple work around fix is to add the first item in the categories list to the list again at the end. Like this:

# data
categories = ['Fuel Economy', 'Reliability', 'Comfort', 'Design', 'Repair Costs', 'Fuel Economy']

I will look for other/better solutions but for now this seems to fix the error. Also I will try to eventually add an example of how to create a radar chart with plotly to GitHub along with the existing examples.

**Comment by RiyaSamanta** [comment]
Thanks, it worked for me

**Comment by RiyaSamanta** [comment]
Thanks, it worked for me.
